---
title: "Probability and Conditional Probability: R functions"
date: Summer 2022
author: "Introduction to Quantitative Social Science"
institute: "Xiaolong Yang \\ University of Tokyo"
output: 
  beamer_presentation:
    theme: "Madrid"
    colortheme: "beaver"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(echo = T,
                      results = "hide") #show most chunks but omit results
library(tidyverse)
```

More advanced function: Practice

```{r, eval=FALSE}
sim_election_summary <- function(p, EV, n = 2048) {
  sims <- map_dbl(seq_len(n), ~ sim_election(p, EV))
  list(tibble(mean = mean(sims),
         p025 = quantile(sims, prob = 0.025),
         p975 = quantile(sims, prob = 0.975)))
}
```


## Todyverse Functions 

```{r, eval = FALSE}
glimpse(starwars) ## transposed version of print(): allows to see all variables
rbinom(x, size, prob) # random generation for the boolean distribution with parameters size and prob  
if_else(condition, true, false, missing = NULL) ## similar to ifelse() in base
complete()
arrange()
group_by()
fill()
```

## ggplot functions

```{r}
geom_vline()
scale_fill_manual()
ylab
xlab ## modify axis
```

