---
title: "Probability and Conditional Probability: R functions"
date: Summer 2022
author: "Introduction to Quantitative Social Science"
institute: "Xiaolong Yang \\ University of Tokyo"
output: 
  beamer_presentation:
    theme: "Madrid"
    colortheme: "beaver"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(echo = T,
                      results = "hide") #show most chunks but omit results
library(tidyverse)
```



## Why & How to write your R function?

**Efficiency: avoid repetitive operations using a single command**

```{r, eval=FALSE}
## To define:
name <- function(...args...) {...body...}

## To call
name(...value...)
```

## Why & How to write your R function?

Example: **How to convert UK shoe size into centimeters?**

Known: 

  - conversion formula: 3 x foot in inches – 22.5 = UK size 
  - 1 inch = 2.4 cm
  

```{r}
uksize_cm <- function(uksize) {
  cm <- (uksize + 22.5) * 2.4 / 3 
  return(cm)
}

uksize_cm(9)
```

## Basic arithmetics (log) 

```{r, eval = FALSE}
## Functions

seq()
lchoose()
lfactorial()

```

